#!/bin/sh

set -e

case "$1" in
	purge|remove)
		rm -f /home/user/.local/share/applications/wolej_harmattan_*
	;;

	failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
